### ISSUE TITLE
speed up conda by using mamba

### ISSUE THREAD

**Issue by mxochicale** [mxochicale/code#33]
> https://www.biostars.org/p/9461665/

**Comment by mxochicale** [comment]
'Namespace' object has no attribute 'no_user'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mxochicale/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/mxochicale/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/home/mxochicale/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/mxochicale/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/mxochicale/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
        exit_code = shell_init(args)
      File "/home/mxochicale/anaconda3/lib/python3.10/site-packages/mamba/mamba_shell_init.py", line 87, in shell_init
        if args.no_user:
    AttributeError: 'Namespace' object has no attribute 'no_user'

`$ /home/mxochicale/anaconda3/condabin/mamba init`

potential solution > 
> I encountered the same problem. The reason might be that you started from scratch but didn't install mamba from Mambaforge. This can be solved by a full installation of mamba from [Mambaforge](https://github.com/conda-forge/miniforge#mambaforge), as this will run the mamba init after the installation of mamba.
https://stackoverflow.com/questions/76000757/mamba-init-error-attributeerror-namespace-object-has-no-attribute-no-user
